name: Bug Report
description: Report a bug in Market Hours
title: "[Bug] <short description>"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🙏
        Please fill out the form below. If you have logs, attach them at the bottom.

  - type: input
    id: game_version
    attributes:
      label: Game version
      description: Find this in the game's title screen or Settings → About.
      placeholder: "e.g. 0.0.1.123"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
        - macOS
        - Linux
        - Steam Deck
        - Other
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: OS version
      placeholder: "e.g. Windows 11 23H2, macOS 14.2"
    validations:
      required: false

  - type: dropdown
    id: distribution
    attributes:
      label: Distribution
      options:
        - Steam
        - Direct (markethoursgame.com)
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Briefly describe the bug.
      placeholder: "e.g. Game freezes when opening the Employees screen after hiring a trader."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: "e.g. Employees screen should open normally."
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to reproduce
      description: If you can reliably reproduce it, list the steps.
      placeholder: |
        1) Start a new game
        2) Recruit first employee
        3) Open Employees screen
        4) ...
    validations:
      required: false

  - type: dropdown
    id: reproducible
    attributes:
      label: How often does it happen?
      options:
        - Every time
        - Often
        - Sometimes
        - Only once
        - Not sure
    validations:
      required: true

  - type: textarea
    id: attachments
    attributes:
      label: Attachments (optional but helpful)
      description: Drag and drop screenshots/videos here. If possible, attach your log file(s) too.
      placeholder: "Attach files here (screenshots, videos, latest.log, crash dump if any)."
    validations:
      required: false

  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy
      description: Please confirm you are not including sensitive personal information in the report.
      options:
        - label: I confirm this report does not contain sensitive personal information.
          required: true
